/*
	An enum of constants used commonly by all files. Put any classes, id prefixes, or other text here.
*/
var Constants = {
	FUNCTION: "list",
	KEYWORD: "keyword",
	OPEN_PAREN_CLASS: "svc-open-paren-class",
	OPEN_PAREN_ID_PREFIX: "svc-open-paren-",
	STATEMENT_HOLDER_CLASS: "svc-statement-holder-class",
	STATEMENT_HOLDER_ID_PREFIX: "svc-statement-holder-",
	CLOSE_PAREN_CLASS: "svc-close-paren-class",
	CLOSE_PAREN_ID_PREFIX: "svc-close-paren-",
	OPEN_PAREN: "(",
	CLOSE_PAREN: ")",
	ID_ATTRIBUTE: "title",
	DIV: "<div></div>",
	SPAN: "<span></span>",
	VARIABLE_CLASS: "svc-variable-class",
	VARIABLE_ID_PREFIX: "svc-variable-",
	KEYWORD_CLASS: "svc-keyword-class",
	WHITESPACE: "  ",
	WHITESPACE_HTML: "&nbsp;",
	BODY: $(document.body),
	STRING: "string",
	NUMBER: "number",
	CONSTANT_CLASS: "svc-constant-class",
	HIGHLIGHTED_CLASS: "svc-highlighted-class",
	REMOVED_CLASS: "svc-removed-class",
	INSERTED_CLASS: "svc-inserted-class",
	ADD: "add",
	REMOVE: "remove",
	INSERT: "insert",
	MOVE: "move",
	RENAME: "rename",
	DIFF_URL: "diff.html?",
	FILE_LIST_URL: "files.php",
	FILE_URL: "file.php",
	A_HTML: "<a></a>",
	BR: "<br/>",
	FIRST_FILE: "file1",
	SECOND_FILE: "file2",
	FIRST_FILE_VERSION: "file1version",
	SECOND_FILE_VERSION: "file2version",
	PATH: "path",
	VERSION: "version"
};
