/*
	An enum of constants used commonly by all files. Put any classes, id prefixes, or other text here.
*/
var Constants = {
	FUNCTION: "list",
	KEYWORD: "keyword",
	OPEN_PAREN_CLASS: "svc-open-paren-class",
	OPEN_PAREN_ID_PREFIX: "svc-open-paren-",
	STATEMENT_HOLDER_CLASS: "svc-statement-holder-class",
	STATEMENT_HOLDER_ID_PREFIX: "svc-statement-holder-",
	CLOSE_PAREN_CLASS: "svc-close-paren-class",
	CLOSE_PAREN_ID_PREFIX: "svc-close-paren-",
	OPEN_PAREN: " (",
	CLOSE_PAREN: ") ",
	ID_ATTRIBUTE: "id",
	DIV: "<div></div>",
	SPAN: "<span></span>",
	VARIABLE_CLASS: "svc-variable-class",
	VARIABLE_ID_PREFIX: "svc-variable-",
	KEYWORD_CLASS: "svc-keyword-class",
	WHITESPACE: "  ",
	WHITESPACE_HTML: "&nbsp;",
	WHITESPACE_CLASS: "svc-whitespace-class",
	HOLDER_CLASS: "svc-holder-class",
	BODY: $(document.body),
	STRING: "string",
	NUMBER: "number",
	COMMENT: "comment",
	COMMENT_CLASS: "svc-comment-class",
	CONSTANT_CLASS: "svc-constant-class",
	HIGHLIGHTED_CLASS: "svc-highlighted-class",
	REMOVED_CLASS: "svc-removed-class",
	INSERTED_CLASS: "svc-inserted-class",
	ADD: "insertion",
	REMOVE: "deletion",
	INSERT: "insertion",
	MOVE: "move",
	RENAME: "rename",
	DIFF_URL: "diff.html?",
	FILE_LIST_URL: "http://128.32.131.41:8080/commit",
	FILE_URL: "http://128.32.131.41:8080/commit/",
	FILE_DIFF_URL: "http://128.32.131.41:8080/diff/",
	A_HTML: "<a></a>",
	BR: "<br/>",
	FIRST_FILE: "file1",
	SECOND_FILE: "file2",
	FIRST_FILE_VERSION: "file1version",
	SECOND_FILE_VERSION: "file2version",
	PATH: "path",
	VERSION: "version",
	MODIFICATION: "modification"
};
